apiVersion: apps/v1
kind: Deployment
metadata:
  name: msproc
  labels:
    app: mosproc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msproc
  template:
    metadata:
      labels:
        app: msproc
    spec:
      nodeSelector:
      containers:
      - image: mspoccr.azurecr.io/vehicle_monitoring:1.18
        name: msrproc
        ports:
        - containerPort: 8082
      imagePullSecrets:
      - name: vechicle